name: LiveTexts
main: EmreTr1\LiveTexts
version: Kaymak
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
author: EmreTr1
description: Like LiveSigns plugin just more basic.
commands:
 lt:
  description: LiveTexts command
